fish_shop:
  outputs:
    dev:
      dataset: diego_pipeline_raw
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: us-west1
      method: service-account
      keyfile: ./keyfile.json
      priority: interactive
      project: savvy-range-365915
      threads: 1
      type: bigquery
  target: dev
